### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '.'

### ISSUE THREAD

**Issue by neelupatel11** [Advestis/htmlmerger#5]
This package is not working. I am facing the below error

"IsADirectoryError: [Errno 21] Is a directory: '.'"

**Comment by ghost** [comment]
Hi, 
Could you provide the full error message, including the previous lines ?

**Comment by neelupatel11** [comment]
**My code**
from htmlmerger import HtmlMerger
merger = HtmlMerger(input_directory="files/")  # result will be in my_htmls/merged.html
merger.merge(clean=True)  # or clean=False to keep the individual files (default behavior)

**Error** 
IsADirectoryError                         Traceback (most recent call last)
/tmp/ipykernel_8322/480352151.py in <cell line: 3>()
      1 from htmlmerger import HtmlMerger
      2 merger = HtmlMerger(input_directory="files/")  # result will be in my_htmls/merged.html
----> 3 merger.merge(clean=True)  # or clean=False to keep the individual files (default behavior)

~/anaconda3/lib/python3.9/site-packages/htmlmerger/htmlmerger.py in merge(self, clean)
    123         if not self.loaded:
    124             self.get_contents()
--> 125         with open(self.output_path, "w") as ofile:
    126             ofile.write(f"{self.header}\n")
    127             for name in self.contents:

IsADirectoryError: [Errno 21] Is a directory: '.'

**Comment by cottephi** [comment]
Fixed

**Comment by ghost** [comment]
Fixed in f9095a0ea1f5bfd7db715284e149c7f7275b2e74

**Comment by neelupatel11** [comment]
it's really great you have solved the issue within no time.
Thank you so much for the response. May i know the reason behind this issue.

**Comment by ghost** [comment]
No problem :)
The reason was me, I made a stupid mistake in the code
